# coding: utf-8

# flake8: noqa

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

__version__ = "1"

# import ApiClient
from api_video_python_sdk.api_client import ApiClient

# import Configuration
from api_video_python_sdk.configuration import Configuration

# import exceptions
from api_video_python_sdk.exceptions import OpenApiException
from api_video_python_sdk.exceptions import ApiAttributeError
from api_video_python_sdk.exceptions import ApiTypeError
from api_video_python_sdk.exceptions import ApiValueError
from api_video_python_sdk.exceptions import ApiKeyError
from api_video_python_sdk.exceptions import ApiException

from api_video_python_sdk.client import ApiVideo
