# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from api_video_python_sdk import ApiVideo

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        apivideo = ApiVideo(
        
            username = 'YOUR_USERNAME',
            password = 'YOUR_PASSWORD',
        
            access_token = 'YOUR_BEARER_TOKEN'
        )
        self.assertIsNotNone(apivideo)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
