# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from api_video_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from api_video_python_sdk.api_response import AsyncGeneratorResponse
from api_video_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from api_video_python_sdk import schemas  # noqa: F401

from api_video_python_sdk.model.model403_error_schema import Model403ErrorSchema as Model403ErrorSchemaSchema
from api_video_python_sdk.model.analytics_plays400_error import AnalyticsPlays400Error as AnalyticsPlays400ErrorSchema
from api_video_python_sdk.model.analytics_plays_response import AnalyticsPlaysResponse as AnalyticsPlaysResponseSchema
from api_video_python_sdk.model.not_found import NotFound as NotFoundSchema

from api_video_python_sdk.type.analytics_plays_response import AnalyticsPlaysResponse
from api_video_python_sdk.type.not_found import NotFound
from api_video_python_sdk.type.model403_error_schema import Model403ErrorSchema
from api_video_python_sdk.type.analytics_plays400_error import AnalyticsPlays400Error

from ...api_client import Dictionary
from api_video_python_sdk.pydantic.not_found import NotFound as NotFoundPydantic
from api_video_python_sdk.pydantic.model403_error_schema import Model403ErrorSchema as Model403ErrorSchemaPydantic
from api_video_python_sdk.pydantic.analytics_plays400_error import AnalyticsPlays400Error as AnalyticsPlays400ErrorPydantic
from api_video_python_sdk.pydantic.analytics_plays_response import AnalyticsPlaysResponse as AnalyticsPlaysResponsePydantic

# Query params
ModelFromSchema = schemas.DateSchema
ToSchema = schemas.DateSchema


class DimensionSchema(
    schemas.EnumBase,
    schemas.StrSchema
):
    
    @schemas.classproperty
    def VIDEO_ID(cls):
        return cls("videoId")
    
    @schemas.classproperty
    def EMITTED_AT(cls):
        return cls("emittedAt")
    
    @schemas.classproperty
    def COUNTRY(cls):
        return cls("country")
    
    @schemas.classproperty
    def DEVICE_TYPE(cls):
        return cls("deviceType")
    
    @schemas.classproperty
    def OPERATING_SYSTEM(cls):
        return cls("operatingSystem")
    
    @schemas.classproperty
    def BROWSER(cls):
        return cls("browser")
FilterSchema = schemas.StrSchema
CurrentPageSchema = schemas.IntSchema
PageSizeSchema = schemas.IntSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
        'from': typing.Union[ModelFromSchema, str, date, ],
        'dimension': typing.Union[DimensionSchema, str, ],
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'to': typing.Union[ToSchema, str, date, ],
        'filter': typing.Union[FilterSchema, str, ],
        'currentPage': typing.Union[CurrentPageSchema, decimal.Decimal, int, ],
        'pageSize': typing.Union[PageSizeSchema, decimal.Decimal, int, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query__from = api_client.QueryParameter(
    name="from",
    style=api_client.ParameterStyle.FORM,
    schema=ModelFromSchema,
    required=True,
    explode=True,
)
request_query_to = api_client.QueryParameter(
    name="to",
    style=api_client.ParameterStyle.FORM,
    schema=ToSchema,
    explode=True,
)
request_query_dimension = api_client.QueryParameter(
    name="dimension",
    style=api_client.ParameterStyle.FORM,
    schema=DimensionSchema,
    required=True,
)
request_query_filter = api_client.QueryParameter(
    name="filter",
    style=api_client.ParameterStyle.FORM,
    schema=FilterSchema,
)
request_query_current_page = api_client.QueryParameter(
    name="currentPage",
    style=api_client.ParameterStyle.FORM,
    schema=CurrentPageSchema,
    explode=True,
)
request_query_page_size = api_client.QueryParameter(
    name="pageSize",
    style=api_client.ParameterStyle.FORM,
    schema=PageSizeSchema,
    explode=True,
)
SchemaFor200ResponseBodyApplicationJson = AnalyticsPlaysResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: AnalyticsPlaysResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: AnalyticsPlaysResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor400ResponseBodyApplicationJson = AnalyticsPlays400ErrorSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: AnalyticsPlays400Error


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: AnalyticsPlays400Error


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
SchemaFor403ResponseBodyApplicationJson = Model403ErrorSchemaSchema


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: Model403ErrorSchema


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: Model403ErrorSchema


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationJson),
    },
)
SchemaFor404ResponseBodyApplicationJson = NotFoundSchema


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: NotFound


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: NotFound


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _get_video_plays_mapped_args(
        self,
        _from: date,
        dimension: str,
        to: typing.Optional[date] = None,
        filter: typing.Optional[str] = None,
        current_page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if _from is not None:
            _query_params["from"] = _from
        if to is not None:
            _query_params["to"] = to
        if dimension is not None:
            _query_params["dimension"] = dimension
        if filter is not None:
            _query_params["filter"] = filter
        if current_page is not None:
            _query_params["currentPage"] = current_page
        if page_size is not None:
            _query_params["pageSize"] = page_size
        args.query = _query_params
        return args

    async def _aget_video_plays_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Get play events for video
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query__from,
            request_query_to,
            request_query_dimension,
            request_query_filter,
            request_query_current_page,
            request_query_page_size,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/analytics/videos/plays',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_video_plays_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Get play events for video
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query__from,
            request_query_to,
            request_query_dimension,
            request_query_filter,
            request_query_current_page,
            request_query_page_size,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/analytics/videos/plays',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetVideoPlaysRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_video_plays(
        self,
        _from: date,
        dimension: str,
        to: typing.Optional[date] = None,
        filter: typing.Optional[str] = None,
        current_page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_video_plays_mapped_args(
            _from=_from,
            dimension=dimension,
            to=to,
            filter=filter,
            current_page=current_page,
            page_size=page_size,
        )
        return await self._aget_video_plays_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get_video_plays(
        self,
        _from: date,
        dimension: str,
        to: typing.Optional[date] = None,
        filter: typing.Optional[str] = None,
        current_page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_video_plays_mapped_args(
            _from=_from,
            dimension=dimension,
            to=to,
            filter=filter,
            current_page=current_page,
            page_size=page_size,
        )
        return self._get_video_plays_oapg(
            query_params=args.query,
        )

class GetVideoPlays(BaseApi):

    async def aget_video_plays(
        self,
        _from: date,
        dimension: str,
        to: typing.Optional[date] = None,
        filter: typing.Optional[str] = None,
        current_page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        validate: bool = False,
        **kwargs,
    ) -> AnalyticsPlaysResponsePydantic:
        raw_response = await self.raw.aget_video_plays(
            _from=_from,
            dimension=dimension,
            to=to,
            filter=filter,
            current_page=current_page,
            page_size=page_size,
            **kwargs,
        )
        if validate:
            return AnalyticsPlaysResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(AnalyticsPlaysResponsePydantic, raw_response.body)
    
    
    def get_video_plays(
        self,
        _from: date,
        dimension: str,
        to: typing.Optional[date] = None,
        filter: typing.Optional[str] = None,
        current_page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        validate: bool = False,
    ) -> AnalyticsPlaysResponsePydantic:
        raw_response = self.raw.get_video_plays(
            _from=_from,
            dimension=dimension,
            to=to,
            filter=filter,
            current_page=current_page,
            page_size=page_size,
        )
        if validate:
            return AnalyticsPlaysResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(AnalyticsPlaysResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        _from: date,
        dimension: str,
        to: typing.Optional[date] = None,
        filter: typing.Optional[str] = None,
        current_page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_video_plays_mapped_args(
            _from=_from,
            dimension=dimension,
            to=to,
            filter=filter,
            current_page=current_page,
            page_size=page_size,
        )
        return await self._aget_video_plays_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        _from: date,
        dimension: str,
        to: typing.Optional[date] = None,
        filter: typing.Optional[str] = None,
        current_page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_video_plays_mapped_args(
            _from=_from,
            dimension=dimension,
            to=to,
            filter=filter,
            current_page=current_page,
            page_size=page_size,
        )
        return self._get_video_plays_oapg(
            query_params=args.query,
        )

