# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from api_video_python_sdk import schemas  # noqa: F401


class LiveStream(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "restreams",
            "liveStreamId",
        }
        
        class properties:
            liveStreamId = schemas.StrSchema
            
            
            class restreams(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['RestreamsResponseObject']:
                        return RestreamsResponseObject
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['RestreamsResponseObject'], typing.List['RestreamsResponseObject']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'restreams':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'RestreamsResponseObject':
                    return super().__getitem__(i)
            name = schemas.StrSchema
            streamKey = schemas.StrSchema
            public = schemas.BoolSchema
        
            @staticmethod
            def assets() -> typing.Type['LiveStreamAssets']:
                return LiveStreamAssets
            playerId = schemas.StrSchema
            broadcasting = schemas.BoolSchema
            createdAt = schemas.DateTimeSchema
            updatedAt = schemas.DateTimeSchema
            __annotations__ = {
                "liveStreamId": liveStreamId,
                "restreams": restreams,
                "name": name,
                "streamKey": streamKey,
                "public": public,
                "assets": assets,
                "playerId": playerId,
                "broadcasting": broadcasting,
                "createdAt": createdAt,
                "updatedAt": updatedAt,
            }
    
    restreams: MetaOapg.properties.restreams
    liveStreamId: MetaOapg.properties.liveStreamId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["liveStreamId"]) -> MetaOapg.properties.liveStreamId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["restreams"]) -> MetaOapg.properties.restreams: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["streamKey"]) -> MetaOapg.properties.streamKey: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["public"]) -> MetaOapg.properties.public: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assets"]) -> 'LiveStreamAssets': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["playerId"]) -> MetaOapg.properties.playerId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["broadcasting"]) -> MetaOapg.properties.broadcasting: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdAt"]) -> MetaOapg.properties.createdAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updatedAt"]) -> MetaOapg.properties.updatedAt: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["liveStreamId", "restreams", "name", "streamKey", "public", "assets", "playerId", "broadcasting", "createdAt", "updatedAt", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["liveStreamId"]) -> MetaOapg.properties.liveStreamId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["restreams"]) -> MetaOapg.properties.restreams: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["streamKey"]) -> typing.Union[MetaOapg.properties.streamKey, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["public"]) -> typing.Union[MetaOapg.properties.public, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assets"]) -> typing.Union['LiveStreamAssets', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["playerId"]) -> typing.Union[MetaOapg.properties.playerId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["broadcasting"]) -> typing.Union[MetaOapg.properties.broadcasting, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdAt"]) -> typing.Union[MetaOapg.properties.createdAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updatedAt"]) -> typing.Union[MetaOapg.properties.updatedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["liveStreamId", "restreams", "name", "streamKey", "public", "assets", "playerId", "broadcasting", "createdAt", "updatedAt", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        restreams: typing.Union[MetaOapg.properties.restreams, list, tuple, ],
        liveStreamId: typing.Union[MetaOapg.properties.liveStreamId, str, ],
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        streamKey: typing.Union[MetaOapg.properties.streamKey, str, schemas.Unset] = schemas.unset,
        public: typing.Union[MetaOapg.properties.public, bool, schemas.Unset] = schemas.unset,
        assets: typing.Union['LiveStreamAssets', schemas.Unset] = schemas.unset,
        playerId: typing.Union[MetaOapg.properties.playerId, str, schemas.Unset] = schemas.unset,
        broadcasting: typing.Union[MetaOapg.properties.broadcasting, bool, schemas.Unset] = schemas.unset,
        createdAt: typing.Union[MetaOapg.properties.createdAt, str, datetime, schemas.Unset] = schemas.unset,
        updatedAt: typing.Union[MetaOapg.properties.updatedAt, str, datetime, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'LiveStream':
        return super().__new__(
            cls,
            *args,
            restreams=restreams,
            liveStreamId=liveStreamId,
            name=name,
            streamKey=streamKey,
            public=public,
            assets=assets,
            playerId=playerId,
            broadcasting=broadcasting,
            createdAt=createdAt,
            updatedAt=updatedAt,
            _configuration=_configuration,
            **kwargs,
        )

from api_video_python_sdk.model.live_stream_assets import LiveStreamAssets
from api_video_python_sdk.model.restreams_response_object import RestreamsResponseObject
