# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from api_video_python_sdk import schemas  # noqa: F401


class RestreamsRequestObject(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Adding restream destinations is optional. However, if you set a restream destination, you must provide all attributes for each destination.
    """


    class MetaOapg:
        required = {
            "streamKey",
            "serverUrl",
            "name",
        }
        
        class properties:
            name = schemas.StrSchema
            serverUrl = schemas.StrSchema
            streamKey = schemas.StrSchema
            __annotations__ = {
                "name": name,
                "serverUrl": serverUrl,
                "streamKey": streamKey,
            }
    
    streamKey: MetaOapg.properties.streamKey
    serverUrl: MetaOapg.properties.serverUrl
    name: MetaOapg.properties.name
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["serverUrl"]) -> MetaOapg.properties.serverUrl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["streamKey"]) -> MetaOapg.properties.streamKey: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "serverUrl", "streamKey", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["serverUrl"]) -> MetaOapg.properties.serverUrl: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["streamKey"]) -> MetaOapg.properties.streamKey: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "serverUrl", "streamKey", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        streamKey: typing.Union[MetaOapg.properties.streamKey, str, ],
        serverUrl: typing.Union[MetaOapg.properties.serverUrl, str, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RestreamsRequestObject':
        return super().__new__(
            cls,
            *args,
            streamKey=streamKey,
            serverUrl=serverUrl,
            name=name,
            _configuration=_configuration,
            **kwargs,
        )
