# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from api_video_python_sdk import schemas  # noqa: F401


class Video(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "videoId",
        }
        
        class properties:
            videoId = schemas.StrSchema
        
            @staticmethod
            def tags() -> typing.Type['VideoTags']:
                return VideoTags
            title = schemas.StrSchema
            description = schemas.StrSchema
            createdAt = schemas.DateTimeSchema
            publishedAt = schemas.DateTimeSchema
            updatedAt = schemas.DateTimeSchema
            
            
            class metadata(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Metadata']:
                        return Metadata
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Metadata'], typing.List['Metadata']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'metadata':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Metadata':
                    return super().__getitem__(i)
        
            @staticmethod
            def source() -> typing.Type['VideoSource']:
                return VideoSource
        
            @staticmethod
            def assets() -> typing.Type['VideoAssets']:
                return VideoAssets
            playerId = schemas.StrSchema
            public = schemas.BoolSchema
            panoramic = schemas.BoolSchema
            mp4Support = schemas.BoolSchema
            __annotations__ = {
                "videoId": videoId,
                "tags": tags,
                "title": title,
                "description": description,
                "createdAt": createdAt,
                "publishedAt": publishedAt,
                "updatedAt": updatedAt,
                "metadata": metadata,
                "source": source,
                "assets": assets,
                "playerId": playerId,
                "public": public,
                "panoramic": panoramic,
                "mp4Support": mp4Support,
            }
    
    videoId: MetaOapg.properties.videoId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["videoId"]) -> MetaOapg.properties.videoId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tags"]) -> 'VideoTags': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdAt"]) -> MetaOapg.properties.createdAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["publishedAt"]) -> MetaOapg.properties.publishedAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updatedAt"]) -> MetaOapg.properties.updatedAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> MetaOapg.properties.metadata: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["source"]) -> 'VideoSource': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assets"]) -> 'VideoAssets': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["playerId"]) -> MetaOapg.properties.playerId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["public"]) -> MetaOapg.properties.public: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["panoramic"]) -> MetaOapg.properties.panoramic: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mp4Support"]) -> MetaOapg.properties.mp4Support: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["videoId", "tags", "title", "description", "createdAt", "publishedAt", "updatedAt", "metadata", "source", "assets", "playerId", "public", "panoramic", "mp4Support", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["videoId"]) -> MetaOapg.properties.videoId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tags"]) -> typing.Union['VideoTags', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> typing.Union[MetaOapg.properties.title, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdAt"]) -> typing.Union[MetaOapg.properties.createdAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["publishedAt"]) -> typing.Union[MetaOapg.properties.publishedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updatedAt"]) -> typing.Union[MetaOapg.properties.updatedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> typing.Union[MetaOapg.properties.metadata, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["source"]) -> typing.Union['VideoSource', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assets"]) -> typing.Union['VideoAssets', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["playerId"]) -> typing.Union[MetaOapg.properties.playerId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["public"]) -> typing.Union[MetaOapg.properties.public, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["panoramic"]) -> typing.Union[MetaOapg.properties.panoramic, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mp4Support"]) -> typing.Union[MetaOapg.properties.mp4Support, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["videoId", "tags", "title", "description", "createdAt", "publishedAt", "updatedAt", "metadata", "source", "assets", "playerId", "public", "panoramic", "mp4Support", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        videoId: typing.Union[MetaOapg.properties.videoId, str, ],
        tags: typing.Union['VideoTags', schemas.Unset] = schemas.unset,
        title: typing.Union[MetaOapg.properties.title, str, schemas.Unset] = schemas.unset,
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        createdAt: typing.Union[MetaOapg.properties.createdAt, str, datetime, schemas.Unset] = schemas.unset,
        publishedAt: typing.Union[MetaOapg.properties.publishedAt, str, datetime, schemas.Unset] = schemas.unset,
        updatedAt: typing.Union[MetaOapg.properties.updatedAt, str, datetime, schemas.Unset] = schemas.unset,
        metadata: typing.Union[MetaOapg.properties.metadata, list, tuple, schemas.Unset] = schemas.unset,
        source: typing.Union['VideoSource', schemas.Unset] = schemas.unset,
        assets: typing.Union['VideoAssets', schemas.Unset] = schemas.unset,
        playerId: typing.Union[MetaOapg.properties.playerId, str, schemas.Unset] = schemas.unset,
        public: typing.Union[MetaOapg.properties.public, bool, schemas.Unset] = schemas.unset,
        panoramic: typing.Union[MetaOapg.properties.panoramic, bool, schemas.Unset] = schemas.unset,
        mp4Support: typing.Union[MetaOapg.properties.mp4Support, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Video':
        return super().__new__(
            cls,
            *args,
            videoId=videoId,
            tags=tags,
            title=title,
            description=description,
            createdAt=createdAt,
            publishedAt=publishedAt,
            updatedAt=updatedAt,
            metadata=metadata,
            source=source,
            assets=assets,
            playerId=playerId,
            public=public,
            panoramic=panoramic,
            mp4Support=mp4Support,
            _configuration=_configuration,
            **kwargs,
        )

from api_video_python_sdk.model.metadata import Metadata
from api_video_python_sdk.model.video_assets import VideoAssets
from api_video_python_sdk.model.video_source import VideoSource
from api_video_python_sdk.model.video_tags import VideoTags
