# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from api_video_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from api_video_python_sdk.api_response import AsyncGeneratorResponse
from api_video_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from api_video_python_sdk import schemas  # noqa: F401

from api_video_python_sdk.model.player_theme_creation_payload import PlayerThemeCreationPayload as PlayerThemeCreationPayloadSchema
from api_video_python_sdk.model.player_theme import PlayerTheme as PlayerThemeSchema

from api_video_python_sdk.type.player_theme import PlayerTheme
from api_video_python_sdk.type.player_theme_creation_payload import PlayerThemeCreationPayload

from ...api_client import Dictionary
from api_video_python_sdk.pydantic.player_theme import PlayerTheme as PlayerThemePydantic
from api_video_python_sdk.pydantic.player_theme_creation_payload import PlayerThemeCreationPayload as PlayerThemeCreationPayloadPydantic

# body param
SchemaForRequestBodyApplicationJson = PlayerThemeCreationPayloadSchema


request_body_player_theme_creation_payload = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
SchemaFor201ResponseBodyApplicationJson = PlayerThemeSchema


@dataclass
class ApiResponseFor201(api_client.ApiResponse):
    body: PlayerTheme


@dataclass
class ApiResponseFor201Async(api_client.AsyncApiResponse):
    body: PlayerTheme


_response_for_201 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor201,
    response_cls_async=ApiResponseFor201Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor201ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _players_0_mapped_args(
        self,
        name: typing.Optional[str] = None,
        text: typing.Optional[str] = None,
        link: typing.Optional[str] = None,
        link_hover: typing.Optional[str] = None,
        link_active: typing.Optional[str] = None,
        track_played: typing.Optional[str] = None,
        track_unplayed: typing.Optional[str] = None,
        track_background: typing.Optional[str] = None,
        background_top: typing.Optional[str] = None,
        background_bottom: typing.Optional[str] = None,
        background_text: typing.Optional[str] = None,
        enable_api: typing.Optional[bool] = None,
        enable_controls: typing.Optional[bool] = None,
        force_autoplay: typing.Optional[bool] = None,
        hide_title: typing.Optional[bool] = None,
        force_loop: typing.Optional[bool] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if name is not None:
            _body["name"] = name
        if text is not None:
            _body["text"] = text
        if link is not None:
            _body["link"] = link
        if link_hover is not None:
            _body["linkHover"] = link_hover
        if link_active is not None:
            _body["linkActive"] = link_active
        if track_played is not None:
            _body["trackPlayed"] = track_played
        if track_unplayed is not None:
            _body["trackUnplayed"] = track_unplayed
        if track_background is not None:
            _body["trackBackground"] = track_background
        if background_top is not None:
            _body["backgroundTop"] = background_top
        if background_bottom is not None:
            _body["backgroundBottom"] = background_bottom
        if background_text is not None:
            _body["backgroundText"] = background_text
        if enable_api is not None:
            _body["enableApi"] = enable_api
        if enable_controls is not None:
            _body["enableControls"] = enable_controls
        if force_autoplay is not None:
            _body["forceAutoplay"] = force_autoplay
        if hide_title is not None:
            _body["hideTitle"] = hide_title
        if force_loop is not None:
            _body["forceLoop"] = force_loop
        args.body = _body
        return args

    async def _aplayers_0_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Create a player
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/players',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_player_theme_creation_payload.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _players_0_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Create a player
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/players',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_player_theme_creation_payload.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class Players0Raw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aplayers_0(
        self,
        name: typing.Optional[str] = None,
        text: typing.Optional[str] = None,
        link: typing.Optional[str] = None,
        link_hover: typing.Optional[str] = None,
        link_active: typing.Optional[str] = None,
        track_played: typing.Optional[str] = None,
        track_unplayed: typing.Optional[str] = None,
        track_background: typing.Optional[str] = None,
        background_top: typing.Optional[str] = None,
        background_bottom: typing.Optional[str] = None,
        background_text: typing.Optional[str] = None,
        enable_api: typing.Optional[bool] = None,
        enable_controls: typing.Optional[bool] = None,
        force_autoplay: typing.Optional[bool] = None,
        hide_title: typing.Optional[bool] = None,
        force_loop: typing.Optional[bool] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._players_0_mapped_args(
            name=name,
            text=text,
            link=link,
            link_hover=link_hover,
            link_active=link_active,
            track_played=track_played,
            track_unplayed=track_unplayed,
            track_background=track_background,
            background_top=background_top,
            background_bottom=background_bottom,
            background_text=background_text,
            enable_api=enable_api,
            enable_controls=enable_controls,
            force_autoplay=force_autoplay,
            hide_title=hide_title,
            force_loop=force_loop,
        )
        return await self._aplayers_0_oapg(
            body=args.body,
            **kwargs,
        )
    
    def players_0(
        self,
        name: typing.Optional[str] = None,
        text: typing.Optional[str] = None,
        link: typing.Optional[str] = None,
        link_hover: typing.Optional[str] = None,
        link_active: typing.Optional[str] = None,
        track_played: typing.Optional[str] = None,
        track_unplayed: typing.Optional[str] = None,
        track_background: typing.Optional[str] = None,
        background_top: typing.Optional[str] = None,
        background_bottom: typing.Optional[str] = None,
        background_text: typing.Optional[str] = None,
        enable_api: typing.Optional[bool] = None,
        enable_controls: typing.Optional[bool] = None,
        force_autoplay: typing.Optional[bool] = None,
        hide_title: typing.Optional[bool] = None,
        force_loop: typing.Optional[bool] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._players_0_mapped_args(
            name=name,
            text=text,
            link=link,
            link_hover=link_hover,
            link_active=link_active,
            track_played=track_played,
            track_unplayed=track_unplayed,
            track_background=track_background,
            background_top=background_top,
            background_bottom=background_bottom,
            background_text=background_text,
            enable_api=enable_api,
            enable_controls=enable_controls,
            force_autoplay=force_autoplay,
            hide_title=hide_title,
            force_loop=force_loop,
        )
        return self._players_0_oapg(
            body=args.body,
        )

class Players0(BaseApi):

    async def aplayers_0(
        self,
        name: typing.Optional[str] = None,
        text: typing.Optional[str] = None,
        link: typing.Optional[str] = None,
        link_hover: typing.Optional[str] = None,
        link_active: typing.Optional[str] = None,
        track_played: typing.Optional[str] = None,
        track_unplayed: typing.Optional[str] = None,
        track_background: typing.Optional[str] = None,
        background_top: typing.Optional[str] = None,
        background_bottom: typing.Optional[str] = None,
        background_text: typing.Optional[str] = None,
        enable_api: typing.Optional[bool] = None,
        enable_controls: typing.Optional[bool] = None,
        force_autoplay: typing.Optional[bool] = None,
        hide_title: typing.Optional[bool] = None,
        force_loop: typing.Optional[bool] = None,
        validate: bool = False,
        **kwargs,
    ) -> PlayerThemePydantic:
        raw_response = await self.raw.aplayers_0(
            name=name,
            text=text,
            link=link,
            link_hover=link_hover,
            link_active=link_active,
            track_played=track_played,
            track_unplayed=track_unplayed,
            track_background=track_background,
            background_top=background_top,
            background_bottom=background_bottom,
            background_text=background_text,
            enable_api=enable_api,
            enable_controls=enable_controls,
            force_autoplay=force_autoplay,
            hide_title=hide_title,
            force_loop=force_loop,
            **kwargs,
        )
        if validate:
            return PlayerThemePydantic(**raw_response.body)
        return api_client.construct_model_instance(PlayerThemePydantic, raw_response.body)
    
    
    def players_0(
        self,
        name: typing.Optional[str] = None,
        text: typing.Optional[str] = None,
        link: typing.Optional[str] = None,
        link_hover: typing.Optional[str] = None,
        link_active: typing.Optional[str] = None,
        track_played: typing.Optional[str] = None,
        track_unplayed: typing.Optional[str] = None,
        track_background: typing.Optional[str] = None,
        background_top: typing.Optional[str] = None,
        background_bottom: typing.Optional[str] = None,
        background_text: typing.Optional[str] = None,
        enable_api: typing.Optional[bool] = None,
        enable_controls: typing.Optional[bool] = None,
        force_autoplay: typing.Optional[bool] = None,
        hide_title: typing.Optional[bool] = None,
        force_loop: typing.Optional[bool] = None,
        validate: bool = False,
    ) -> PlayerThemePydantic:
        raw_response = self.raw.players_0(
            name=name,
            text=text,
            link=link,
            link_hover=link_hover,
            link_active=link_active,
            track_played=track_played,
            track_unplayed=track_unplayed,
            track_background=track_background,
            background_top=background_top,
            background_bottom=background_bottom,
            background_text=background_text,
            enable_api=enable_api,
            enable_controls=enable_controls,
            force_autoplay=force_autoplay,
            hide_title=hide_title,
            force_loop=force_loop,
        )
        if validate:
            return PlayerThemePydantic(**raw_response.body)
        return api_client.construct_model_instance(PlayerThemePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        name: typing.Optional[str] = None,
        text: typing.Optional[str] = None,
        link: typing.Optional[str] = None,
        link_hover: typing.Optional[str] = None,
        link_active: typing.Optional[str] = None,
        track_played: typing.Optional[str] = None,
        track_unplayed: typing.Optional[str] = None,
        track_background: typing.Optional[str] = None,
        background_top: typing.Optional[str] = None,
        background_bottom: typing.Optional[str] = None,
        background_text: typing.Optional[str] = None,
        enable_api: typing.Optional[bool] = None,
        enable_controls: typing.Optional[bool] = None,
        force_autoplay: typing.Optional[bool] = None,
        hide_title: typing.Optional[bool] = None,
        force_loop: typing.Optional[bool] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._players_0_mapped_args(
            name=name,
            text=text,
            link=link,
            link_hover=link_hover,
            link_active=link_active,
            track_played=track_played,
            track_unplayed=track_unplayed,
            track_background=track_background,
            background_top=background_top,
            background_bottom=background_bottom,
            background_text=background_text,
            enable_api=enable_api,
            enable_controls=enable_controls,
            force_autoplay=force_autoplay,
            hide_title=hide_title,
            force_loop=force_loop,
        )
        return await self._aplayers_0_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        name: typing.Optional[str] = None,
        text: typing.Optional[str] = None,
        link: typing.Optional[str] = None,
        link_hover: typing.Optional[str] = None,
        link_active: typing.Optional[str] = None,
        track_played: typing.Optional[str] = None,
        track_unplayed: typing.Optional[str] = None,
        track_background: typing.Optional[str] = None,
        background_top: typing.Optional[str] = None,
        background_bottom: typing.Optional[str] = None,
        background_text: typing.Optional[str] = None,
        enable_api: typing.Optional[bool] = None,
        enable_controls: typing.Optional[bool] = None,
        force_autoplay: typing.Optional[bool] = None,
        hide_title: typing.Optional[bool] = None,
        force_loop: typing.Optional[bool] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._players_0_mapped_args(
            name=name,
            text=text,
            link=link,
            link_hover=link_hover,
            link_active=link_active,
            track_played=track_played,
            track_unplayed=track_unplayed,
            track_background=track_background,
            background_top=background_top,
            background_bottom=background_bottom,
            background_text=background_text,
            enable_api=enable_api,
            enable_controls=enable_controls,
            force_autoplay=force_autoplay,
            hide_title=hide_title,
            force_loop=force_loop,
        )
        return self._players_0_oapg(
            body=args.body,
        )

