# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from api_video_python_sdk.paths.auth_api_key.post import GetBearerToken
from api_video_python_sdk.paths.auth_refresh.post import RefreshBearerToken
from api_video_python_sdk.apis.tags.advanced_authentication_api_raw import AdvancedAuthenticationApiRaw


class AdvancedAuthenticationApi(
    GetBearerToken,
    RefreshBearerToken,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AdvancedAuthenticationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AdvancedAuthenticationApiRaw(api_client)
