# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from api_video_python_sdk.paths.auth_api_key.post import GetBearerTokenRaw
from api_video_python_sdk.paths.auth_refresh.post import RefreshBearerTokenRaw


class AdvancedAuthenticationApiRaw(
    GetBearerTokenRaw,
    RefreshBearerTokenRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
