# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from api_video_python_sdk.paths.analytics_live_streams_plays.get import GetLiveStreamPlays
from api_video_python_sdk.paths.analytics_videos_plays.get import GetVideoPlays
from api_video_python_sdk.apis.tags.analytics_api_raw import AnalyticsApiRaw


class AnalyticsApi(
    GetLiveStreamPlays,
    GetVideoPlays,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AnalyticsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AnalyticsApiRaw(api_client)
