# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from api_video_python_sdk.paths.videos_video_id_chapters_language.delete import DeleteChapterInLanguageRaw
from api_video_python_sdk.paths.videos_video_id_chapters_language.get import GetChapterByLanguageRaw
from api_video_python_sdk.paths.videos_video_id_chapters.get import ListByVideoRaw
from api_video_python_sdk.paths.videos_video_id_chapters_language.post import UploadVttFileRaw


class ChaptersApiRaw(
    DeleteChapterInLanguageRaw,
    GetChapterByLanguageRaw,
    ListByVideoRaw,
    UploadVttFileRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
