# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from api_video_python_sdk.paths.live_streams.post import CreateLivestreamObjectRaw
from api_video_python_sdk.paths.live_streams_live_stream_id.delete import DeleteLivestreamRaw
from api_video_python_sdk.paths.live_streams_live_stream_id_thumbnail.delete import DeleteThumbnailRaw
from api_video_python_sdk.paths.live_streams_live_stream_id.get import GetLivestreamByIdRaw
from api_video_python_sdk.paths.live_streams.get import ListAllRaw
from api_video_python_sdk.paths.live_streams_live_stream_id.patch import UpdateLivestreamObjectRaw
from api_video_python_sdk.paths.live_streams_live_stream_id_thumbnail.post import UploadThumbnailRaw


class LiveStreamsApiRaw(
    CreateLivestreamObjectRaw,
    DeleteLivestreamRaw,
    DeleteThumbnailRaw,
    GetLivestreamByIdRaw,
    ListAllRaw,
    UpdateLivestreamObjectRaw,
    UploadThumbnailRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
