# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from api_video_python_sdk.paths.players_player_id.delete import DeletePlayer
from api_video_python_sdk.paths.players_player_id.get import GetThemeByPlayerId
from api_video_python_sdk.paths.players.get import Players
from api_video_python_sdk.paths.players.post import Players0
from api_video_python_sdk.paths.players_player_id_logo.delete import RemoveLogo
from api_video_python_sdk.paths.players_player_id.patch import UpdatePlayerDetails
from api_video_python_sdk.paths.players_player_id_logo.post import UploadLogo
from api_video_python_sdk.apis.tags.player_themes_api_raw import PlayerThemesApiRaw


class PlayerThemesApi(
    DeletePlayer,
    GetThemeByPlayerId,
    Players,
    Players0,
    RemoveLogo,
    UpdatePlayerDetails,
    UploadLogo,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PlayerThemesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PlayerThemesApiRaw(api_client)
