# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from api_video_python_sdk.paths.watermarks.get import ListAll
from api_video_python_sdk.paths.watermarks.post import Watermark
from api_video_python_sdk.paths.watermarks_watermark_id.delete import Watermark0
from api_video_python_sdk.apis.tags.watermarks_api_raw import WatermarksApiRaw


class WatermarksApi(
    ListAll,
    Watermark,
    Watermark0,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WatermarksApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WatermarksApiRaw(api_client)
