# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from api_video_python_sdk.paths.webhooks.post import CreateWebhookEvent
from api_video_python_sdk.paths.webhooks_webhook_id.delete import DeleteWebhook
from api_video_python_sdk.paths.webhooks_webhook_id.get import GetDetailsById
from api_video_python_sdk.paths.webhooks.get import ListAll
from api_video_python_sdk.apis.tags.webhooks_api_raw import WebhooksApiRaw


class WebhooksApi(
    CreateWebhookEvent,
    DeleteWebhook,
    GetDetailsById,
    ListAll,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WebhooksApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WebhooksApiRaw(api_client)
