# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

import unittest

import api_video_python_sdk
from api_video_python_sdk.model.captions_list_response import CaptionsListResponse
from api_video_python_sdk import configuration


class TestCaptionsListResponse(unittest.TestCase):
    """CaptionsListResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
