# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from api_video_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from api_video_python_sdk.api_response import AsyncGeneratorResponse
from api_video_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from api_video_python_sdk import schemas  # noqa: F401

from api_video_python_sdk.model.video_creation_payload import VideoCreationPayload as VideoCreationPayloadSchema
from api_video_python_sdk.model.video_clip import VideoClip as VideoClipSchema
from api_video_python_sdk.model.video import Video as VideoSchema
from api_video_python_sdk.model.metadata import Metadata as MetadataSchema
from api_video_python_sdk.model.video_watermark import VideoWatermark as VideoWatermarkSchema
from api_video_python_sdk.model.bad_request import BadRequest as BadRequestSchema
from api_video_python_sdk.model.video_creation_payload_tags import VideoCreationPayloadTags as VideoCreationPayloadTagsSchema

from api_video_python_sdk.type.video_watermark import VideoWatermark
from api_video_python_sdk.type.metadata import Metadata
from api_video_python_sdk.type.bad_request import BadRequest
from api_video_python_sdk.type.video import Video
from api_video_python_sdk.type.video_clip import VideoClip
from api_video_python_sdk.type.video_creation_payload import VideoCreationPayload
from api_video_python_sdk.type.video_creation_payload_tags import VideoCreationPayloadTags

from ...api_client import Dictionary
from api_video_python_sdk.pydantic.video_creation_payload_tags import VideoCreationPayloadTags as VideoCreationPayloadTagsPydantic
from api_video_python_sdk.pydantic.metadata import Metadata as MetadataPydantic
from api_video_python_sdk.pydantic.video_clip import VideoClip as VideoClipPydantic
from api_video_python_sdk.pydantic.video import Video as VideoPydantic
from api_video_python_sdk.pydantic.bad_request import BadRequest as BadRequestPydantic
from api_video_python_sdk.pydantic.video_creation_payload import VideoCreationPayload as VideoCreationPayloadPydantic
from api_video_python_sdk.pydantic.video_watermark import VideoWatermark as VideoWatermarkPydantic

from . import path

# body param
SchemaForRequestBodyApplicationJson = VideoCreationPayloadSchema


request_body_video_creation_payload = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
_auth = [
    'apiKey',
]
SchemaFor201ResponseBodyApplicationJson = VideoSchema


@dataclass
class ApiResponseFor201(api_client.ApiResponse):
    body: Video


@dataclass
class ApiResponseFor201Async(api_client.AsyncApiResponse):
    body: Video


_response_for_201 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor201,
    response_cls_async=ApiResponseFor201Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor201ResponseBodyApplicationJson),
    },
)
SchemaFor202ResponseBodyApplicationJson = VideoSchema


@dataclass
class ApiResponseFor202(api_client.ApiResponse):
    body: Video


@dataclass
class ApiResponseFor202Async(api_client.AsyncApiResponse):
    body: Video


_response_for_202 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor202,
    response_cls_async=ApiResponseFor202Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor202ResponseBodyApplicationJson),
    },
)
SchemaFor400ResponseBodyApplicationJson = BadRequestSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: BadRequest


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: BadRequest


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '201': _response_for_201,
    '202': _response_for_202,
    '400': _response_for_400,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _create_object_mapped_args(
        self,
        title: str,
        tags: typing.Optional[VideoCreationPayloadTags] = None,
        description: typing.Optional[str] = None,
        source: typing.Optional[str] = None,
        public: typing.Optional[bool] = None,
        panoramic: typing.Optional[bool] = None,
        mp4_support: typing.Optional[bool] = None,
        player_id: typing.Optional[str] = None,
        metadata: typing.Optional[typing.List[Metadata]] = None,
        clip: typing.Optional[VideoClip] = None,
        watermark: typing.Optional[VideoWatermark] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if tags is not None:
            _body["tags"] = tags
        if title is not None:
            _body["title"] = title
        if description is not None:
            _body["description"] = description
        if source is not None:
            _body["source"] = source
        if public is not None:
            _body["public"] = public
        if panoramic is not None:
            _body["panoramic"] = panoramic
        if mp4_support is not None:
            _body["mp4Support"] = mp4_support
        if player_id is not None:
            _body["playerId"] = player_id
        if metadata is not None:
            _body["metadata"] = metadata
        if clip is not None:
            _body["clip"] = clip
        if watermark is not None:
            _body["watermark"] = watermark
        args.body = _body
        return args

    async def _acreate_object_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        ApiResponseFor202Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Create a video object
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/videos',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_video_creation_payload.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _create_object_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor201,
        ApiResponseFor202,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Create a video object
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/videos',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_video_creation_payload.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class CreateObjectRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def acreate_object(
        self,
        title: str,
        tags: typing.Optional[VideoCreationPayloadTags] = None,
        description: typing.Optional[str] = None,
        source: typing.Optional[str] = None,
        public: typing.Optional[bool] = None,
        panoramic: typing.Optional[bool] = None,
        mp4_support: typing.Optional[bool] = None,
        player_id: typing.Optional[str] = None,
        metadata: typing.Optional[typing.List[Metadata]] = None,
        clip: typing.Optional[VideoClip] = None,
        watermark: typing.Optional[VideoWatermark] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        ApiResponseFor202Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_object_mapped_args(
            title=title,
            tags=tags,
            description=description,
            source=source,
            public=public,
            panoramic=panoramic,
            mp4_support=mp4_support,
            player_id=player_id,
            metadata=metadata,
            clip=clip,
            watermark=watermark,
        )
        return await self._acreate_object_oapg(
            body=args.body,
            **kwargs,
        )
    
    def create_object(
        self,
        title: str,
        tags: typing.Optional[VideoCreationPayloadTags] = None,
        description: typing.Optional[str] = None,
        source: typing.Optional[str] = None,
        public: typing.Optional[bool] = None,
        panoramic: typing.Optional[bool] = None,
        mp4_support: typing.Optional[bool] = None,
        player_id: typing.Optional[str] = None,
        metadata: typing.Optional[typing.List[Metadata]] = None,
        clip: typing.Optional[VideoClip] = None,
        watermark: typing.Optional[VideoWatermark] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        ApiResponseFor202,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_object_mapped_args(
            title=title,
            tags=tags,
            description=description,
            source=source,
            public=public,
            panoramic=panoramic,
            mp4_support=mp4_support,
            player_id=player_id,
            metadata=metadata,
            clip=clip,
            watermark=watermark,
        )
        return self._create_object_oapg(
            body=args.body,
        )

class CreateObject(BaseApi):

    async def acreate_object(
        self,
        title: str,
        tags: typing.Optional[VideoCreationPayloadTags] = None,
        description: typing.Optional[str] = None,
        source: typing.Optional[str] = None,
        public: typing.Optional[bool] = None,
        panoramic: typing.Optional[bool] = None,
        mp4_support: typing.Optional[bool] = None,
        player_id: typing.Optional[str] = None,
        metadata: typing.Optional[typing.List[Metadata]] = None,
        clip: typing.Optional[VideoClip] = None,
        watermark: typing.Optional[VideoWatermark] = None,
        validate: bool = False,
        **kwargs,
    ) -> VideoPydantic:
        raw_response = await self.raw.acreate_object(
            title=title,
            tags=tags,
            description=description,
            source=source,
            public=public,
            panoramic=panoramic,
            mp4_support=mp4_support,
            player_id=player_id,
            metadata=metadata,
            clip=clip,
            watermark=watermark,
            **kwargs,
        )
        if validate:
            return VideoPydantic(**raw_response.body)
        return api_client.construct_model_instance(VideoPydantic, raw_response.body)
    
    
    def create_object(
        self,
        title: str,
        tags: typing.Optional[VideoCreationPayloadTags] = None,
        description: typing.Optional[str] = None,
        source: typing.Optional[str] = None,
        public: typing.Optional[bool] = None,
        panoramic: typing.Optional[bool] = None,
        mp4_support: typing.Optional[bool] = None,
        player_id: typing.Optional[str] = None,
        metadata: typing.Optional[typing.List[Metadata]] = None,
        clip: typing.Optional[VideoClip] = None,
        watermark: typing.Optional[VideoWatermark] = None,
        validate: bool = False,
    ) -> VideoPydantic:
        raw_response = self.raw.create_object(
            title=title,
            tags=tags,
            description=description,
            source=source,
            public=public,
            panoramic=panoramic,
            mp4_support=mp4_support,
            player_id=player_id,
            metadata=metadata,
            clip=clip,
            watermark=watermark,
        )
        if validate:
            return VideoPydantic(**raw_response.body)
        return api_client.construct_model_instance(VideoPydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        title: str,
        tags: typing.Optional[VideoCreationPayloadTags] = None,
        description: typing.Optional[str] = None,
        source: typing.Optional[str] = None,
        public: typing.Optional[bool] = None,
        panoramic: typing.Optional[bool] = None,
        mp4_support: typing.Optional[bool] = None,
        player_id: typing.Optional[str] = None,
        metadata: typing.Optional[typing.List[Metadata]] = None,
        clip: typing.Optional[VideoClip] = None,
        watermark: typing.Optional[VideoWatermark] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        ApiResponseFor202Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_object_mapped_args(
            title=title,
            tags=tags,
            description=description,
            source=source,
            public=public,
            panoramic=panoramic,
            mp4_support=mp4_support,
            player_id=player_id,
            metadata=metadata,
            clip=clip,
            watermark=watermark,
        )
        return await self._acreate_object_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        title: str,
        tags: typing.Optional[VideoCreationPayloadTags] = None,
        description: typing.Optional[str] = None,
        source: typing.Optional[str] = None,
        public: typing.Optional[bool] = None,
        panoramic: typing.Optional[bool] = None,
        mp4_support: typing.Optional[bool] = None,
        player_id: typing.Optional[str] = None,
        metadata: typing.Optional[typing.List[Metadata]] = None,
        clip: typing.Optional[VideoClip] = None,
        watermark: typing.Optional[VideoWatermark] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        ApiResponseFor202,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_object_mapped_args(
            title=title,
            tags=tags,
            description=description,
            source=source,
            public=public,
            panoramic=panoramic,
            mp4_support=mp4_support,
            player_id=player_id,
            metadata=metadata,
            clip=clip,
            watermark=watermark,
        )
        return self._create_object_oapg(
            body=args.body,
        )

