# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class AnalyticsPlays400Error(BaseModel):
    # A description of the error that occurred.
    title: typing.Optional[str] = Field(None, alias='title')

    # A link to the error documentation.
    type: typing.Optional[str] = Field(None, alias='type')

    # The HTTP status code.
    status: typing.Optional[int] = Field(None, alias='status')

    # A solution for the error.
    detail: typing.Optional[str] = Field(None, alias='detail')

    # The name of the parameter that caused the error.
    name: typing.Optional[str] = Field(None, alias='name')
    class Config:
        arbitrary_types_allowed = True
