# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from api_video_python_sdk.pydantic.additional_bad_request_errors import AdditionalBadRequestErrors

class BadRequest(BaseModel):
    # A description of the error that occurred.
    title: typing.Optional[str] = Field(None, alias='title')

    # A link to the error documentation.
    type: typing.Optional[str] = Field(None, alias='type')

    # The name of the parameter that caused the error.
    name: typing.Optional[str] = Field(None, alias='name')

    # The HTTP status code.
    status: typing.Optional[int] = Field(None, alias='status')

    # Returns any additional problems in the request in an array of objects.
    problems: typing.Optional[typing.List[AdditionalBadRequestErrors]] = Field(None, alias='problems')
    class Config:
        arbitrary_types_allowed = True
