# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class LiveStreamSessionSession(BaseModel):
    # A unique identifier for your session. You can use this to track what happens during a specific session.
    session_id: typing.Optional[str] = Field(None, alias='sessionId')

    # When the session started, with the date and time presented in ISO-8601 format.
    loaded_at: typing.Optional[datetime] = Field(None, alias='loadedAt')

    # When the session ended, with the date and time presented in ISO-8601 format.
    ended_at: typing.Optional[datetime] = Field(None, alias='endedAt')
    class Config:
        arbitrary_types_allowed = True
