# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from api_video_python_sdk.pydantic.pagination_link import PaginationLink

class Pagination(BaseModel):
    links: typing.List[PaginationLink] = Field(alias='links')

    # Total number of items that exist.
    items_total: typing.Optional[int] = Field(None, alias='itemsTotal')

    # Number of items listed in the current page.
    pages_total: typing.Optional[int] = Field(None, alias='pagesTotal')

    # Maximum number of item per page.
    page_size: typing.Optional[int] = Field(None, alias='pageSize')

    # The current page index.
    current_page: typing.Optional[int] = Field(None, alias='currentPage')

    # The number of items on the current page.
    current_page_items: typing.Optional[int] = Field(None, alias='currentPageItems')
    class Config:
        arbitrary_types_allowed = True
