# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class PlayerThemeUploadLogoPayload(BaseModel):
    # The name of the file you want to use for your logo.
    file: typing.IO = Field(alias='file')

    # A public link that you want to advertise in your player. For example, you could add a link to your company. When a viewer clicks on your logo, they will be taken to this address.
    link: typing.Optional[str] = Field(None, alias='link')
    class Config:
        arbitrary_types_allowed = True
