# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class TokenUploadPayload(BaseModel):
    # The path to the video you want to upload.
    file: typing.IO = Field(alias='file')

    # The video id returned by the first call to this endpoint in a large video upload scenario.
    video_id: typing.Optional[str] = Field(None, alias='videoId')
    class Config:
        arbitrary_types_allowed = True
