# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class UploadToken(BaseModel):
    # The unique identifier for the token you will use to authenticate an upload.
    token: typing.Optional[str] = Field(None, alias='token')

    # Time-to-live - how long the upload token is valid for.
    ttl: typing.Optional[int] = Field(None, alias='ttl')

    # When the token was created, displayed in ISO-8601 format.
    created_at: typing.Optional[datetime] = Field(None, alias='createdAt')

    # When the token expires, displayed in ISO-8601 format.
    expires_at: typing.Optional[typing.Optional[datetime]] = Field(None, alias='expiresAt')
    class Config:
        arbitrary_types_allowed = True
