# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from api_video_python_sdk.pydantic.video_source_live_stream_link import VideoSourceLiveStreamLink

class VideoSourceLiveStream(BaseModel):
    # The unique identifier for the live stream.
    live_stream_id: typing.Optional[str] = Field(None, alias='liveStreamId')

    links: typing.Optional[typing.List[VideoSourceLiveStreamLink]] = Field(None, alias='links')
    class Config:
        arbitrary_types_allowed = True
