# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class VideoWatermark(BaseModel):
    # id of the watermark
    id: typing.Optional[str] = Field(None, alias='id')

    # Distance expressed in px or % between the top-border of the video and the watermark-image.
    top: typing.Optional[str] = Field(None, alias='top')

    # Distance expressed in px or % between the left-border of the video and the watermark-image.
    left: typing.Optional[str] = Field(None, alias='left')

    # Distance expressed in px or % between the bottom-border of the video and the watermark-image.
    bottom: typing.Optional[str] = Field(None, alias='bottom')

    # Distance expressed in px or % between the right-border of the video and the watermark-image.
    right: typing.Optional[str] = Field(None, alias='right')

    # Width of the watermark-image relative to the video if expressed in %. Otherwise a fixed width. NOTE: To keep intrinsic watermark-image width use `initial`.
    width: typing.Optional[str] = Field(None, alias='width')

    # Height of the watermark-image relative to the video if expressed in %. Otherwise a fixed height. NOTE: To keep intrinsic watermark-image height use `initial`.
    height: typing.Optional[str] = Field(None, alias='height')

    # Opacity expressed in % only to specify the degree of the watermark-image transparency with the video.
    opacity: typing.Optional[str] = Field(None, alias='opacity')
    class Config:
        arbitrary_types_allowed = True
