# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from api_video_python_sdk.pydantic.metadata import Metadata

class VideoSessionSession(BaseModel):
    # The unique identifier for the session that you can use to track what happens during it.
    session_id: typing.Optional[str] = Field(None, alias='sessionId')

    # When the video session started, presented in ISO-8601 format.
    loaded_at: typing.Optional[datetime] = Field(None, alias='loadedAt')

    # When the video session ended, presented in ISO-8601 format.
    ended_at: typing.Optional[datetime] = Field(None, alias='endedAt')

    # A list of key value pairs that you use to provide metadata for your video. These pairs can be made dynamic, allowing you to segment your audience. You can also just use the pairs as another way to tag and categorize your videos.
    metadata: typing.Optional[typing.List[Metadata]] = Field(None, alias='metadata')
    class Config:
        arbitrary_types_allowed = True
