# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from api_video_python_sdk.pydantic.metadata import Metadata
from api_video_python_sdk.pydantic.video_clip import VideoClip
from api_video_python_sdk.pydantic.video_creation_payload_tags import VideoCreationPayloadTags
from api_video_python_sdk.pydantic.video_watermark import VideoWatermark

class VideoCreationPayload(BaseModel):
    # The title of your new video.
    title: str = Field(alias='title')

    tags: typing.Optional[VideoCreationPayloadTags] = Field(None, alias='tags')

    # A brief description of your video.
    description: typing.Optional[str] = Field(None, alias='description')

    # You can either add a video already on the web, by entering the URL of the video, or you can also enter the `videoId` of one of the videos you already have on your api.video acccount, and this will generate a copy of your video. Creating a copy of a video can be especially useful if you want to keep your original video and trim or apply a watermark onto the copy you would create.
    source: typing.Optional[str] = Field(None, alias='source')

    # Default: True. If set to `false` the video will become private. More information on private videos can be found [here](https://docs.api.video/delivery-analytics/video-privacy-access-management)
    public: typing.Optional[bool] = Field(None, alias='public')

    # Indicates if your video is a 360/immersive video.
    panoramic: typing.Optional[bool] = Field(None, alias='panoramic')

    # Enables mp4 version in addition to streamed version.
    mp4_support: typing.Optional[bool] = Field(None, alias='mp4Support')

    # The unique identification number for your video player.
    player_id: typing.Optional[str] = Field(None, alias='playerId')

    # A list of key value pairs that you use to provide metadata for your video. These pairs can be made dynamic, allowing you to segment your audience. Read more on [dynamic metadata](https://api.video/blog/endpoints/dynamic-metadata/).
    metadata: typing.Optional[typing.List[Metadata]] = Field(None, alias='metadata')

    clip: typing.Optional[VideoClip] = Field(None, alias='clip')

    watermark: typing.Optional[VideoWatermark] = Field(None, alias='watermark')
    class Config:
        arbitrary_types_allowed = True
