# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class VideoSessionOs(BaseModel):
    # The version of the operating system.
    version: typing.Optional[str] = Field(None, alias='version')

    # The name of the operating system.
    name: typing.Optional[str] = Field(None, alias='name')

    # The nickname for the operating system, often representing the version.
    shortname: typing.Optional[str] = Field(None, alias='shortname')
    class Config:
        arbitrary_types_allowed = True
