# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from api_video_python_sdk.pydantic.video_status_encoding import VideoStatusEncoding
from api_video_python_sdk.pydantic.video_status_ingest import VideoStatusIngest

class VideoStatus(BaseModel):
    ingest: typing.Optional[VideoStatusIngest] = Field(None, alias='ingest')

    encoding: typing.Optional[VideoStatusEncoding] = Field(None, alias='encoding')
    class Config:
        arbitrary_types_allowed = True
