# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class VideoSessionReferrer(BaseModel):
    # The link the viewer used to reach the video session.
    url: typing.Optional[typing.Optional[str]] = Field(None, alias='url')

    # How they arrived at the site, for example organic or paid. Organic meaning they found it themselves and paid meaning they followed a link from an advertisement.
    medium: typing.Optional[str] = Field(None, alias='medium')

    # The source the referrer came from to the video session. For example if they searched through google to find the stream.
    source: typing.Optional[str] = Field(None, alias='source')

    # The search term they typed to arrive at the video session.
    search_term: typing.Optional[str] = Field(None, alias='searchTerm')
    class Config:
        arbitrary_types_allowed = True
