# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAccessToken(TypedDict):
    pass

class OptionalAccessToken(TypedDict, total=False):
    # The access token containing security credentials allowing you to acccess the API. The token lasts for one hour.
    access_token: str

    # The type of token you have.
    token_type: str

    # A token you can use to get the next access token when your current access token expires.
    refresh_token: str

    # Lists the time in seconds when your access token expires. It lasts for one hour.
    expires_in: int

class AccessToken(RequiredAccessToken, OptionalAccessToken):
    pass
