# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


RequiredBytesRange = TypedDict("RequiredBytesRange", {
    })

OptionalBytesRange = TypedDict("OptionalBytesRange", {
    # The starting point for the range of bytes for a chunk of a video.
    "from": int,

    # The ending point for the range of bytes for a chunk of a video.
    "to": int,

    # The total number of expected bytes.
    "total": int,
    }, total=False)

class BytesRange(RequiredBytesRange, OptionalBytesRange):
    pass
