# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from api_video_python_sdk.type.live_stream_assets import LiveStreamAssets
from api_video_python_sdk.type.restreams_response_object import RestreamsResponseObject

class RequiredLiveStream(TypedDict):
    # The unique identifier for the live stream. Live stream IDs begin with \"li.\"
    liveStreamId: str

    # Returns the list of RTMP restream destinations.
    restreams: typing.List[RestreamsResponseObject]

class OptionalLiveStream(TypedDict, total=False):
    # The name of your live stream.
    name: str

    # The unique, private stream key that you use to begin streaming.
    streamKey: str

    # Whether your video can be viewed by everyone, or requires authentication to see it. A setting of false will require a unique token for each view. Learn more about the Private Video feature [here](https://docs.api.video/delivery-analytics/video-privacy-access-management).
    public: bool

    assets: LiveStreamAssets

    # The unique identifier for the player.
    playerId: str

    # Whether or not you are broadcasting the live video you recorded for others to see. True means you are broadcasting to viewers, false means you are not.
    broadcasting: bool

    # When the player was created, presented in ISO-8601 format.
    createdAt: datetime

    # When the player was last updated, presented in ISO-8601 format.
    updatedAt: datetime

class LiveStream(RequiredLiveStream, OptionalLiveStream):
    pass
