# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredLiveStreamSessionDevice(TypedDict):
    pass

class OptionalLiveStreamSessionDevice(TypedDict, total=False):
    # What the type is like desktop, laptop, mobile.
    type: str

    # If known, what the brand of the device is, like Apple, Dell, etc.
    vendor: str

    # The specific model of the device, if known.
    model: str

class LiveStreamSessionDevice(RequiredLiveStreamSessionDevice, OptionalLiveStreamSessionDevice):
    pass
