# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredLiveStreamSessionLocation(TypedDict):
    pass

class OptionalLiveStreamSessionLocation(TypedDict, total=False):
    # The country of the viewer of the live stream.
    country: str

    # The city of the viewer of the live stream.
    city: str

class LiveStreamSessionLocation(RequiredLiveStreamSessionLocation, OptionalLiveStreamSessionLocation):
    pass
