# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredLiveStreamSessionSession(TypedDict):
    pass

class OptionalLiveStreamSessionSession(TypedDict, total=False):
    # A unique identifier for your session. You can use this to track what happens during a specific session.
    sessionId: str

    # When the session started, with the date and time presented in ISO-8601 format.
    loadedAt: datetime

    # When the session ended, with the date and time presented in ISO-8601 format.
    endedAt: datetime

class LiveStreamSessionSession(RequiredLiveStreamSessionSession, OptionalLiveStreamSessionSession):
    pass
