# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredModel403ErrorSchema(TypedDict):
    pass

class OptionalModel403ErrorSchema(TypedDict, total=False):
    # A description of the error that occurred.
    title: str

    # A link to the error documentation.
    type: str

    # The name of the parameter that caused the error.
    name: typing.Optional[str]

    # The HTTP status code.
    status: int

class Model403ErrorSchema(RequiredModel403ErrorSchema, OptionalModel403ErrorSchema):
    pass
