# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


RequiredPlayerSessionEvent = TypedDict("RequiredPlayerSessionEvent", {
    })

OptionalPlayerSessionEvent = TypedDict("OptionalPlayerSessionEvent", {
    # Possible values are: ready, play, pause, resume, seek.backward, seek.forward, end
    "type": str,

    # When an event occurred, presented in ISO-8601 format.
    "emittedAt": datetime,

    "at": int,

    "from": int,

    "to": int,
    }, total=False)

class PlayerSessionEvent(RequiredPlayerSessionEvent, OptionalPlayerSessionEvent):
    pass
