# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPlayerThemeUpdatePayload(TypedDict):
    pass

class OptionalPlayerThemeUpdatePayload(TypedDict, total=False):
    # Add a name for your player theme here.
    name: str

    # RGBA color for timer text. Default: rgba(255, 255, 255, 1)
    text: str

    # RGBA color for all controls. Default: rgba(255, 255, 255, 1)
    link: str

    # RGBA color for all controls when hovered. Default: rgba(255, 255, 255, 1)
    linkHover: str

    # RGBA color for the play button when hovered.
    linkActive: str

    # RGBA color playback bar: played content. Default: rgba(88, 131, 255, .95)
    trackPlayed: str

    # RGBA color playback bar: downloaded but unplayed (buffered) content. Default: rgba(255, 255, 255, .35)
    trackUnplayed: str

    # RGBA color playback bar: background. Default: rgba(255, 255, 255, .2)
    trackBackground: str

    # RGBA color: top 50% of background. Default: rgba(0, 0, 0, .7)
    backgroundTop: str

    # RGBA color: bottom 50% of background. Default: rgba(0, 0, 0, .7)
    backgroundBottom: str

    # RGBA color for title text. Default: rgba(255, 255, 255, 1)
    backgroundText: str

    # enable/disable player SDK access. Default: true
    enableApi: bool

    # enable/disable player controls. Default: true
    enableControls: bool

    # enable/disable player autoplay. Default: false
    forceAutoplay: bool

    # enable/disable title. Default: false
    hideTitle: bool

    # enable/disable looping. Default: false
    forceLoop: bool

class PlayerThemeUpdatePayload(RequiredPlayerThemeUpdatePayload, OptionalPlayerThemeUpdatePayload):
    pass
