# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTokenCreationPayload(TypedDict):
    pass

class OptionalTokenCreationPayload(TypedDict, total=False):
    # Time in seconds that the token will be active. A value of 0 means that the token has no exipration date. The default is to have no expiration.
    ttl: int

class TokenCreationPayload(RequiredTokenCreationPayload, OptionalTokenCreationPayload):
    pass
