# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredVideoStatusEncodingMetadata(TypedDict):
    pass

class OptionalVideoStatusEncodingMetadata(TypedDict, total=False):
    # The width of the video in pixels.
    width: typing.Optional[int]

    # The height of the video in pixels.
    height: typing.Optional[int]

    # The number of bits processed per second.
    bitrate: typing.Optional[typing.Union[int, float]]

    # The length of the video.
    duration: typing.Optional[int]

    # The frequency with which consecutive images or frames appear on a display. Shown in this API as frames per second (fps).
    framerate: typing.Optional[int]

    # How many samples per second a digital audio system uses to record an audio signal. The higher the rate, the higher the frequencies that can be recorded. They are presented in this API using hertz.
    samplerate: typing.Optional[int]

    # The method used to compress and decompress digital video. API Video supports all codecs in the libavcodec library. 
    videoCodec: typing.Optional[str]

    # The method used to compress and decompress digital audio for your video.
    audioCodec: typing.Optional[str]

    aspectRatio: typing.Optional[str]

class VideoStatusEncodingMetadata(RequiredVideoStatusEncodingMetadata, OptionalVideoStatusEncodingMetadata):
    pass
