# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from api_video_python_sdk.type.quality import Quality
from api_video_python_sdk.type.video_status_encoding_metadata import VideoStatusEncodingMetadata

class RequiredVideoStatusEncoding(TypedDict):
    pass

class OptionalVideoStatusEncoding(TypedDict, total=False):
    # Whether the video is playable or not.
    playable: bool

    # Available qualities the video can be viewed in.
    qualities: typing.List[Quality]

    metadata: VideoStatusEncodingMetadata

class VideoStatusEncoding(RequiredVideoStatusEncoding, OptionalVideoStatusEncoding):
    pass
