# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from api_video_python_sdk.type.bytes_range import BytesRange
from api_video_python_sdk.type.video_status_ingest_received_parts import VideoStatusIngestReceivedParts

class RequiredVideoStatusIngest(TypedDict):
    pass

class OptionalVideoStatusIngest(TypedDict, total=False):
    # There are four possible statuses depending on how you provide a video file: - `uploading` - the API is gathering the video source file from an upload. - `uploaded` - the video file is fully uploaded. - `ingesting` - the API is gathering the video source file from either a URL, or from cloning. - `ingested` - the video file is fully stored. 
    status: str

    # The size of your file in bytes.
    filesize: typing.Optional[int]

    # The total number of bytes received, listed for each chunk of the upload.
    receivedBytes: typing.List[BytesRange]

    receivedParts: VideoStatusIngestReceivedParts

class VideoStatusIngest(RequiredVideoStatusIngest, OptionalVideoStatusIngest):
    pass
