# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredVideoAssets(TypedDict):
    pass

class OptionalVideoAssets(TypedDict, total=False):
    # This is the manifest URL. For HTTP Live Streaming (HLS), when a HLS video stream is initiated, the first file to download is the manifest. This file has the extension M3U8, and provides the video player with information about the various bitrates available for streaming.
    hls: str

    # Code to use video from a third party website
    iframe: str

    # Raw url of the player.
    player: str

    # Poster of the video.
    thumbnail: str

    # Available only if mp4Support is enabled. Raw mp4 url.
    mp4: str

class VideoAssets(RequiredVideoAssets, OptionalVideoAssets):
    pass
