# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredVideoSessionOs(TypedDict):
    pass

class OptionalVideoSessionOs(TypedDict, total=False):
    # The version of the operating system.
    version: str

    # The name of the operating system.
    name: str

    # The nickname for the operating system, often representing the version.
    shortname: str

class VideoSessionOs(RequiredVideoSessionOs, OptionalVideoSessionOs):
    pass
