# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredWatermark(TypedDict):
    pass

class OptionalWatermark(TypedDict, total=False):
    # The unique identifier of the watermark.
    watermarkId: str

    # When the watermark was created, presented in ISO-8601 format.
    createdAt: datetime

class Watermark(RequiredWatermark, OptionalWatermark):
    pass
