# coding: utf-8

"""
    api.video

    api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from api_video_python_sdk.type.webhook_events import WebhookEvents

class RequiredWebhook(TypedDict):
    pass

class OptionalWebhook(TypedDict, total=False):
    # Unique identifier of the webhook
    webhookId: str

    # When an webhook was created, presented in ISO-8601 format.
    createdAt: datetime

    events: WebhookEvents

    # URL of the webhook
    url: str

class Webhook(RequiredWebhook, OptionalWebhook):
    pass
